services:

  db:
    image: mysql:8.0
    container_name: crud_mysql

    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: crud_password
      MYSQL_ROOT_PASSWORD: rootpassword

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      interval: 5s
      retries: 10

    restart: always

    volumes:
      - mysql_data:/var/lib/mysql


  web:
    build:
      context: C:\xampp\htdocs\crud
      dockerfile: Dockerfile

    container_name: crud_php

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:80"

    restart: always


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: crud_phpmyadmin

    depends_on:
      db:
        condition: service_healthy

    environment:
      PMA_HOST: db
      PMA_PORT: 3306

    ports:
      - "8081:80"

    restart: always


volumes:
  mysql_data: