name: PHP CRUD CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Hub secret
        run: |
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is EMPTY"
            exit 1
          else
            echo "DOCKERHUB_TOKEN is PRESENT"
          fi

      - name: Check Docker Hub username
        run: |
          if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is EMPTY"
            exit 1
          else
            echo "DOCKERHUB_USERNAME is PRESENT"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/php-crud-devops:latest .

      - name: Push Docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/php-crud-devops:latest